# Generated by Django 4.0.1 on 2022-01-23 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOS_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'BOS Areas',
            },
        ),
        migrations.CreateModel(
            name='BOS_shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'BOS shifts',
            },
        ),
        migrations.CreateModel(
            name='BOS_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'BOS topics',
            },
        ),
        migrations.CreateModel(
            name='BOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comments', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.bos_area')),
                ('Shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.bos_shift')),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.bos_topic')),
            ],
            options={
                'verbose_name_plural': 'BOS Entries',
            },
        ),
    ]
