# Generated by Django 4.0.1 on 2022-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
