# Generated by Django 4.0.1 on 2022-01-23 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bos', '0002_bos_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bos',
            name='User',
        ),
    ]
