# Generated by Django 4.0.1 on 2022-01-29 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bos', '0002_testclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testclass',
            options={'verbose_name_plural': 'Testclass'},
        ),
    ]
