# Generated by Django 4.0.1 on 2022-01-29 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bos', '0003_alter_testclass_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testclass',
        ),
    ]
