# Generated by Django 4.0.1 on 2022-01-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bos', '0004_bos_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bos',
            name='created_by',
        ),
    ]
