# Generated by Django 4.0.1 on 2022-01-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bos', '0004_delete_testclass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BOS_topic',
            new_name='Topic',
        ),
        migrations.AlterModelOptions(
            name='bos',
            options={'verbose_name_plural': 'BOS Conversations'},
        ),
        migrations.AlterModelOptions(
            name='bos_area',
            options={'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='bos_shift',
            options={'verbose_name_plural': 'Shifts'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name_plural': 'Topics'},
        ),
    ]
