# Generated by Django 4.0.1 on 2022-01-29 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bos', '0005_rename_bos_topic_topic_alter_bos_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BOS_shift',
            new_name='Shift',
        ),
    ]
