# Generated by Django 4.0.1 on 2022-01-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bos', '0006_rename_bos_shift_shift'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BOS_area',
            new_name='Area',
        ),
    ]
