# Generated by Django 4.0.1 on 2022-01-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bos', '0007_remove_bos_id_bos_bos_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bos',
            name='BOS_id',
        ),
        migrations.AddField(
            model_name='bos',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
