# Generated by Django 4.0.1 on 2022-01-30 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='permit_to_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.area')),
            ],
            options={
                'verbose_name': 'Permit to work',
                'verbose_name_plural': 'Permits to work',
            },
        ),
    ]
