# Generated by Django 4.0.1 on 2022-01-29 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bos', '0007_rename_bos_area_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='permit_to_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.area')),
            ],
        ),
    ]
