# Generated by Django 4.0.1 on 2022-01-29 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permit_to_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permit_to_work',
            options={'verbose_name_plural': 'Permits to work'},
        ),
    ]
